/**
 * Project 3DScanner
 */


#ifndef _OPERATIONMODE_H
#define _OPERATIONMODE_H

enum OperationMode { OM_IDLE, OM_FREE_RUN_CAPTURE, OM_CAPTURE_FRAME_SEQUENCE, OM_PROCESSING_STEREO, OM_PROCESSING_PCC };

#endif //_OPERATIONMODE_H
